name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: "main"
  
env:
  REGISTRY: docker.io/ashwini73
  IMAGE_NAME: spring-petclinic-1

jobs:          
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login      
        uses: docker/login-action@v3.3.0
        with:
          username: ashwini73
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          #labels: ${{ steps.meta.outputs.labels }}
