name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: "main"
  
env:
  REGISTRY: docker.io/ashwini73
  IMAGE_NAME: spring-petclinic

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ github.sha }}
          #labels: ${{ steps.meta.outputs.labels }}
