name: Deploy to GKE

# on:
#   workflow_run:
#     workflows:
#       - Build and Push Docker Image
#     types:
#       - completed

on:
  push:
    branches: "main"

env:
  REGISTRY: docker.io/ashwini73
  IMAGE_NAME: spring-petclinic-1
  GKE_CLUSTER: test-gke
  GKE_ZONE: us-east1-b

jobs:
  deploy_to_gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Image Tag
        run: |
          IMAGE_TAG="${{ github.event.workflow_run.outputs.image_tag }}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          service_account_key: ${{ secrets.GKE_KEY }}
          project_id: platform-infra
      
      - name: Set up GCP credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_KEY }}
          
      - run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: platform-infra 
          
      # - name: Configure kubectl
      #   run: |
      #     gcloud container clusters get-credentials test-gke --zone us-east1-b --project platform-infra

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/spring-petclinic spring-petclinic=${IMAGE_TAG}
